### ISSUE TITLE
Host Match Detection broken for URLs with ports

### ISSUE THREAD

**Issue by NicholasFlamy** [bitwarden/android#5084]
### Steps To Reproduce

https://github.com/bitwarden/mobile/issues/2970
1. Save an autofill item for a URL with a port.
2. See how it behaves on sites.

### Expected Result

Works correctly. Or at least works like the old app.

### Actual Result

Doesn't work.

### Build Version

2025.3.0

### What server are you connecting to?

Self-host

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by S-Kakar** [comment]
Thank you for your report! We've added this to our internal board for review.
ID: PM-20513

**Comment by NicholasFlamy** [comment]
Note: #4531 is focused on Host detection not working WHICH IS A KNOWN AND REPRODUCIBLE ISSUE CAUSED BY CHROMIUM. This issue is focused on the fact that the new app behaves different from the old one.

**Comment by NicholasFlamy** [comment]
Big difference #1 is that leaving out the URL scheme, `http://` or `https://`, makes the autofill not work if Match Detection is set to Host.

Big difference #2 is that Accessibility Autofill no longer handles ports. On the old app, enabling both accessibility and inline autofill meant the inline showed all options for that base domain which the accessibility button to open the Bitwarden app would open the app to just the properly mathing URLs.

**Comment by NicholasFlamy** [comment]
Small, unrelated thing: Great job on the native app. It LITERALLY takes less than a 1/4 second to open to the main screen when opening it from the Android home screen.
Seriously, great job! (I would like a compact mode appearance option but overall great.)

**Comment by SaintPatrck** [comment]
Hi @NicholasFlamy,

There is a limitation with the Autofill framework that prevents us from matching based on port, path, and query string parameters. They are completely omitted from the request we receive. I left more details about this limitation on https://github.com/bitwarden/mobile/issues/2124#issuecomment-2839759140.

The Accessibility behavior you're describing should be resolved with #5118.

I'm not able to replicate the issue with inline autofill and accessibility being enabled at the same time. Could you elaborate on the behavior you're experiencing when both are enabled?

**Comment by NicholasFlamy** [comment]
> The Accessibility behavior you're describing should be resolved with [#5118](https://github.com/bitwarden/android/pull/5118).

I hope it does, I read the description and it seems to address both parts of the issue.


> I'm not able to replicate the issue with inline autofill and accessibility being enabled at the same time. Could you elaborate on the behavior you're experiencing when both are enabled?

On the old app, when I had both enabled, I would have inline auto-fill suggestions (with Android Autofill limitations) and I would have an accessibility popup to open the Bitwarden app (it may have had autofill options but I think it sometimes simply had the open Bitwarden app button).

On the new app inline autofill takes precedence and seems to "disable" accessibility autofill. (Without actually toggling the switch in the settings.) On the new app I don't get accessibility autofill popups while inline autofill is enabled.

The main reason I like the old app's behavior, is because I often find inline autofill to be faster and I prefer it, but on my sites where port matters, I would tap the accessibility button to open the Bitwarden app, and it would show me the autofill options for that site with the correct port.

**Comment by NicholasFlamy** [comment]
> The Accessibility overlay that you're expecting was omitted from the native rewrite.

Damn, I really liked that feature because it did what Google was too incompetent to do.

**Comment by NicholasFlamy** [comment]
> Due to the limitations I mentioned earlier with the Autofill framework, this means the autofill pop-up and inline suggestions are not going to mirror the exact behavior of the legacy app.

I agree. I am disappointed that the accessibility overlay wasn't implemented in the native app because that was my workaround for Google's incompetence with the Autofill framework.

**Comment by masterflitzer** [comment]
> There is a limitation with the Autofill framework that prevents us from matching based on port, path, and query string parameters. They are completely omitted from the request we receive.

would it be possible to still show the entries that don't match exactly? because no entries showing up is kinda bad for usability

example:
when we have the url "https://example.com:4433/test" i understand that the autofill framework will only send "https://example.com" (or even just "example.com"?), so instead of not showing any entries, show the partially matching ones (only when there are no exact matches)

**Comment by JunoArc** [comment]
> > There is a limitation with the Autofill framework that prevents us from matching based on port, path, and query string parameters. They are completely omitted from the request we receive.
> 
> would it be possible to still show the entries that don't match exactly? because no entries showing up is kinda bad for usability
> 
> example:
> when we have the url "https://example.com:4433/test" i understand that the autofill framework will only send "https://example.com" (or even just "example.com"?), so instead of not showing any entries, show the partially matching ones (only when there are no exact matches)

This is how it worked in the past I think. It was listing all the passwords for the base url without the port and you had to scroll to find it.

**Comment by NicholasFlamy** [comment]
> would it be possible to still show the entries that don't match exactly?

It currently does (at least for me), at the time there was a bug that was causing it to not always show.

**Comment by stefanheinen** [comment]
Hey! Any progress in this?

**Comment by NicholasFlamy** [comment]
> Hey! Any progress in this?

You should go bug Google about their incompetence with Android Autofill.

**Comment by hmoffatt** [comment]
> would it be possible to still show the entries that don't match exactly? because no entries showing up is kinda bad for usability

Yes, please. I have vault entries set to "starts with" that never match either - it would be helpful if Bitwarden on Android treated that as a host match, rather than ignoring them completely.

**Comment by NicholasFlamy** [comment]
> > would it be possible to still show the entries that don't match exactly? because no entries showing up is kinda bad for usability
> 
> Yes, please. I have vault entries set to "starts with" that never match either - it would be helpful if Bitwarden on Android treated that as a host match, rather than ignoring them completely.

Check if they include http:// or https://. Whether you include or exclude the scheme might affect whether they show up.

Edit: but yes, it should include those regardless

**Comment by hmoffatt** [comment]
> Check if they include http:// or https://. Whether you include or exclude the scheme might affect whether they show up.

They do include https. I gave my full example over on the forum at https://community.bitwarden.com/t/account-wont-match/98085

**Comment by travisterrell** [comment]
I recognize that these are tracked elsewhere, so I'm not sure if this is the right place to throw in the thumbs up or not, but this regression has been a major pain for me! I can use starts with to get approximately the same result as port matching, though less accurately. But yes, just a vote to indicate that this is affecting more people.
