### ISSUE TITLE
Autofill stopped working

### ISSUE THREAD

**Issue by kroese** [bitwarden/android#5341]
### Steps To Reproduce

Since recently autofill stopped working on my device. It is a Samsung S23 and it may be related to the the update to OneUI 7.0 / Android 15.

I have Bitwarden configured as the default autofill service, it has all the right permissions in accesibility, excluded from battery saving, etc. 

### Expected Result

See the autofill popup when selecting the password field in Samsung Internet and other apps.

### Actual Result

No popup

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/5128bdec-3d04-4196-bcc0-7619a8646f2e)
![Image](https://github.com/user-attachments/assets/39454747-4a21-43d7-a616-5293dcc3dcdf)
![Image](https://github.com/user-attachments/assets/6dda6ff0-f7fb-4614-9a14-b0049c889715)
![Image](https://github.com/user-attachments/assets/dc8567c6-6107-4daf-894b-4fdd6d69a46c)

### Build Version

2025.5.0 (20269)

### What server are you connecting to?

Self-host

### Self-host Server Version

Vaultwarden

### Environment Details

Device: Samsung S23
Android: 15
OneUI: 7.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Hi @kroese,

Do you happen to have "Use inline autofill" enabled?

If you do, and your keyboard supports inline suggestions, the pop-up you're expecting will not be shown.

**Comment by kroese** [comment]
@SaintPatrck OMG! Thank you so much, that was it! 

However, two more questions:

- I use Google GBoard keyboard, and I have autocorrect/spelling suggestions disabled, so maybe that is why I also didnt see the inline suggestions? Or maybe GBoard doesnt support them at all. But it would be very nice if the Bitwarden client would check if your current keyboard supports them before allowing you to enable inline suggestions.

- I never switched that setting to ON as far as I remember. Suddenly autofill stopped working and I do not think I manually enabled that toggle?

In any case, I now see the autofill popups again in the text field, so my problem is solved.

**Comment by SaintPatrck** [comment]
I'm glad to hear that solved your issue!

>I use Google GBoard keyboard, and I have autocorrect/spelling suggestions disabled, so maybe that is why I also didn't see the inline suggestions? Or maybe GBoard doesn't support them at all.

Gboard does support it but "Show suggestion strip" under "Text correction" settings must also be enabled since the same bar is used for autofill suggestions. What's curious to me, is that you are not seeing the pop-up when "Show suggestion strip" is disabled, if that's the setting you were referring to. In my testing the pop-up appeared even with "Use inline autofill" enabled in Bitwarden when "Show suggestion strip" was disabled in GBoard. There may be other settings in GBoard causing interference.

>But it would be very nice if the Bitwarden client would check if your current keyboard supports them before allowing you to enable inline suggestions.

I agree! Thank you for the excellent suggestion. We'll investigate this as a future improvement. 

>I never switched that setting to ON as far as I remember. Suddenly autofill stopped working and I do not think I manually enabled that toggle?

We do enable inline by default when autofill is turned on. This is something we can re-assess as we consider checking the active keyboards support for inline autofill.

**Comment by ghnp5** [comment]
wow... same here!!

I never manually enabled "Use inline autofill", so I had no idea why Bitwarden stopped working for me.

I tried to check many things, like battery optimization, accessibility, device administrators, etc etc...

I went on Bitwarden settings, disabled autofill and enabled again... still not working.

I was about to raise an Issue here, and found this.
Disabled "Use inline autofill", and it's working again!!

I have my keyboard suggestions disabled. I hate that feature :)

**Comment by columbusanimaladvocates** [comment]
That didn't fix it for me.

**Comment by Aashishkebab** [comment]
Didn't fix for me in Vivaldi. Or any other browser.

**Comment by Ri-Dearg** [comment]
> Hi [@kroese](https://github.com/kroese),
> 
> Do you happen to have "Use inline autofill" enabled?
> 
> If you do, and your keyboard supports inline suggestions, the pop-up you're expecting will not be shown.

Okay, so I had the issue that the popup wasn't working because I had inline autofill turned on... Now it is working. 

**However**, previously I had these two options available to use at the same time. They weren't exclusive for me. I could have both the on-screen popup and the Inline showing. I don't remember how long ago it was, but it was that way for a few years until maybe this year. 

There is no reason that this behaviour should have been changed.

- These are two, separate options in the menu which can both be toggled on.
- There is no help text indicating they are exclusive.
-  there is no visual signal e.g. Toggling one option on greys out the other.
- They are often useful for different scenarios. For example, I have loads of logins to certain sites and inline is unclear, the popup is much easier.
- The inline is faster for simple logins. 
- the popup box often detects fields that inline does not. But if I have inline turned on, the box never shows even if a field could be detected. 
- the user should be able to decide what combo suits them anyway. 

This should be returned to its previous behaviour.

**Comment by Aashishkebab** [comment]
Why is this issue closed?

**Comment by SaintPatrck** [comment]
Hi @Ri-Dearg 

> However, previously I had these two options available to use at the same time. They weren't exclusive for me. I could have both the on-screen popup and the Inline showing. I don't remember how long ago it was, but it was that way for a few years until maybe this year.

You are absolutely correct. Both the pop-up and inline suggestions were presented prior to our migration to native applications. That behavior was achieved by enabling Bitwarden **Accessibility** Service, which operates separately from the traditional **Autofill** Service used by other credential managers. 

Since these are two completely separate services, we were able to inject a pop-up using Accessibility APIs and also provide suggestions to the Autofill service for displaying suggestions Inline. When using only the **Autofill** Service, pop-up and inline suggestions are mutually exclusive, and this is common across all of the credential managers I've worked with.

> This should be returned to its previous behavior.

While I do understand this is an inconvenient change in behavior, due to significant performance overhead and UI issues resulting from constantly scanning the user's screen for input fields, we are not considering adding it back at this time. Now, the "Autofill" Quick Tile must be manually clicked to trigger a one-time scan of the screen. If fillable fields are detected, your vault will open with matching suggestions. The pop-up has been completely removed from **Accessibility** Services, so it will not show even when tapping the "Autofill" Quick Tile. It is only displayed when the Pop-up options is selected in Autofill settings.

> the popup box often detects fields that inline does not. 

This is actually a different issue entirely, due to a limitations within the **Autofill** Service. The **Autofill** Service does not provide URI port and path information so some of our matching options are inherently limited. On the other hand, the **Accessibility** Service allows Bitwarden to read _everything_ on the screen so we're often able to capture the full URI, allowing us to provide more refined and accurate suggestions.

We, and other credential managers, have reported the lack of URL information to Google through their Issue Tracker. Feel free to +1 these reports to increase likely-hood of them being addressed.

https://issuetracker.google.com/issues/413521641
https://issuetracker.google.com/issues/378464307

**Comment by SaintPatrck** [comment]
@Aashishkebab this ticket was closed because the author, and others, confirmed the problem has been resolved.

**Comment by Aashishkebab** [comment]
But the issue hasn't been resolved. And somebody else just filed the same issue again. 

AutoFill is incredibly broken.

**Comment by Ri-Dearg** [comment]
> 
> While I do understand this is an inconvenient change in behavior, due to significant performance overhead and UI issues resulting from constantly scanning the user's screen for input fields, we are not considering adding it back at this time. Now, the "Autofill" Quick Tile must be manually clicked to trigger a one-time scan of the screen. If fillable fields are detected, your vault will open with matching suggestions. The pop-up has been completely removed from **Accessibility** Services, so it will not show even when tapping the "Autofill" Quick Tile. It is only displayed when the Pop-up options is selected in Autofill settings.
> 

I don't see why I can't have the option of both modes? If I want the greater overhead and greater accessibility, why can't I select it as an alternative? If someone prefers the current implementation, that mode could be selected. 

More importantly (and seemingly not considered despite the importance), this change **is not accessible**.

Now, I have to see autofill isn't working, pull down the quick settings/expand them, click the accessibility tile, open the vault, select the login, and it may still not work correctly. That's 4/5 steps and a range of finger motions just to attempt to fill in a form.

Previously, I would open the vault if locked and then select the login. 2 steps if I had to unlock, only 1 click otherwise, and I would have already known if it was working because it would show on the page if the form was detected. This is _actually_ accessible.

The service is not solely for ease-of-use. The change is not just "inconvenient", it greatly diminishes the core point of an **accessibility** service—making it accessible to all people.

**Comment by Aashishkebab** [comment]
The AutoFill quick toggle _doesn't work_ half the time. And there were never any noticeable performance issues with the previous method.
